name: clamav
description: ClamAV TCP / Unix socket client for Dart.
version: 0.1.0
homepage: https://github.com/mskayali/calmav
repository: https://github.com/mskayali/calmav
issue_tracker: https://github.com/mskayali/calmav/issues


environment:
  sdk: ^3.9.2


dev_dependencies:
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.25.6
